# .lintstagedrc.yml

# Apply ESLint to JavaScript/TypeScript files
'.{js, jsx, ts, tsx, vue}':
  - prettier --write
  - eslint --fix

# Apply vue auto sort Tailwind CSS class
'.{vue}':
  - prettier --write